var d=600,e=400,f,g=16,k=0.4,l=6,m,n=50,q=14,r=5,s,t,u,w=3,z=4,A=0.6,B=1.6,C=null,D=null,E=null,F=!1,G=0;
function I(a,b,c){this.next=null;this.d=c;1===c&&(this.size=s);2===c&&(this.size=t);3===c&&(this.size=u);c=-(c-w-1)*A;this.b=(Math.random()*c+B)*(0.5>Math.random()?-1:1);this.c=(Math.random()*c+B)*(0.5>Math.random()?-1:1);this.x=a-this.size+Math.random()*this.size;this.y=b-this.size+Math.random()*this.size;this.frame=Math.ceil(10*Math.random());this.a=document.createElement("img");this.a.style.position="absolute";this.a.style.left=Math.round(this.x)+"px";this.a.style.top=Math.round(this.y)+"px";this.a.src=
"images/ameba"+this.d+"_"+this.d+".png";document.getElementById("game").appendChild(this.a)}I.prototype.move=function(){this.frame+=0.5;19<=this.frame&&(this.frame=1);this.x+=this.b;this.y+=this.c;this.x>d&&(this.x=-u);this.x<-u&&(this.x=d);this.y>e&&(this.y=-u);this.y<-u&&(this.y=e);null!==this.a&&(this.a.style.left=Math.round(this.x)+"px",this.a.style.top=Math.round(this.y)+"px",this.a.src="images/ameba"+this.d+"_"+(1+Math.abs(10-Math.floor(this.frame)))+".png")};
I.prototype.remove=function(){null!==this.a&&(document.getElementById("game").removeChild(this.a),this.a=null)};function J(a,b,c,h){this.next=null;this.x=a;this.y=b;this.b=c*q;this.c=h*q;this.time=n;this.a=document.createElement("img");this.a.style.position="absolute";this.a.style.left=Math.round(this.x)+"px";this.a.style.top=Math.round(this.y)+"px";this.a.src="images/ammo.png";document.getElementById("game").appendChild(this.a)}
J.prototype.move=function(){this.x+=this.b;this.y+=this.c;this.x>d&&(this.x=-u);this.x<-u&&(this.x=d);this.y>e&&(this.y=-u);this.y<-u&&(this.y=e);--this.time;null!==this.a&&(this.a.style.left=Math.round(this.x)+"px",this.a.style.top=Math.round(this.y)+"px")};J.prototype.remove=function(){null!==this.a&&(document.getElementById("game").removeChild(this.a),this.a=null)};
function K(){this.rotation=90;this.x=d/2-f/2;this.y=e/2-f/2;this.e=this.f=this.c=this.b=0;this.a=document.createElement("img");this.a.src="images/ship5.png";this.a.style.position="absolute";this.a.style.left=Math.round(this.x)+"px";this.a.style.top=Math.round(this.y)+"px";document.getElementById("game").appendChild(this.a)}
K.prototype.move=function(){this.rotation+=this.e;0>this.rotation&&(this.rotation=359+this.rotation);359<this.rotation&&(this.rotation-=359);var a=Math.floor(this.rotation/(360/g)),b=-Math.sin(2*Math.PI/g*a);this.b+=Math.cos(2*Math.PI/g*a)*this.f;this.c+=b*this.f;b=Math.sqrt(this.b*this.b+this.c*this.c);10<b&&(this.b/=b,this.c/=b,this.b*=10,this.c*=10);this.x+=this.b;this.y+=this.c;this.b*=0.99;this.c*=0.99;this.x>d&&(this.x=-u);this.x<-u&&(this.x=d);this.y>e&&(this.y=-u);this.y<-u&&(this.y=e);this.a.src=
"images/ship"+(a+1)+".png";this.a.style.left=Math.round(this.x)+"px";this.a.style.top=Math.round(this.y)+"px"};
function L(){C.move();for(var a=E;null!==a;)a.move(),a=a.next;++G;for(var b=null,c=D;null!==c;){c.move();for(var h=null,p=null,a=E;null!==a;){var x=a.x+a.size/2,H=a.y+a.size/2,v=x-(c.x+m/2),y=H-(c.y+m/2);if(Math.sqrt(v*v+y*y)<=a.size/2){c.time=-1;if(1<a.d)for(v=0;v<z;++v)y=h,h=new I(x,H,a.d-1),h.next=y;null===p?E=a.next:p.next=a.next;a.remove()}else p=a;a=a.next}null!==h&&(null===p?E=h:p.next=h);0>c.time&&(null===b?D=c.next:b.next=c.next,c.remove());b=c;c=c.next}}
function M(a){a=(a||window.event).keyCode;if(38===a||87===a||73===a)C.f=k;else if(37===a||65===a||74===a)C.e=l;else if(39===a||68===a||76===a)C.e=-l;else if(32===a||90===a||77===a){if(!F&&G>r){var b=Math.floor(C.rotation/(360/g)),c=Math.cos(2*Math.PI/g*b),b=-Math.sin(2*Math.PI/g*b),h=C.x+f/2-m/2+c*f/2,p=C.y+f/2-m/2+b*f/2;if(null===D)D=new J(h,p,c,b);else{var x=D;D=new J(h,p,c,b);D.next=x}G=0}F=!0}return!(32===a||37===a||38===a||39===a||40===a)}
function N(a){a=(a||window.event).keyCode;if(38===a||87===a||73===a)C.f=0;else if(37===a||65===a||74===a)C.e=0;else if(39===a||68===a||76===a)C.e=0;else if(32===a||90===a||77===a)F=!1;return!(32===a||37===a||38===a||39===a||40===a)}for(var O=[],P=0;48>P;++P)O.push(new Image);for(P=1;16>=P;++P)O[P-1].src="images/ship"+P+".png";for(P=1;10>=P;++P)O[16+P-1].src="images/ameba1_"+P+".png";for(P=1;10>=P;++P)O[26+P-1].src="images/ameba2_"+P+".png";for(P=1;10>=P;++P)O[36+P-1].src="images/ameba3_"+P+".png";
O[46].src="images/ammo.png";O[47].src="images/background.jpg";window.onload=function(){f=O[0].width;s=O[16].width;t=O[26].width;u=O[36].width;m=O[46].width;C=new K;var a=d/6,b=e/5;E=new I(a,b,w);E.next=new I(3*a,b,w);E.next.next=new I(5*a,b,w);E.next.next.next=new I(a,4*b,w);E.next.next.next.next=new I(3*a,4*b,w);E.next.next.next.next.next=new I(5*a,4*b,w);document.onkeydown=M;document.onkeyup=N;setInterval(L,20)};